MAJOR=9
MINOR=7
SERVICEPACK=0
BUILD_NUMBER=10531
#For milestone and ga
MILESTONE=m7
#For patch
PATCH_NUMBER=17
	#xap | dotnet | cpp | cloudify
PATCH_TYPE=dotnet


VERSION=${MAJOR}.${MINOR}.${SERVICEPACK}

REPOSITORY=/export/builds
BUILD_DIR=${REPOSITORY}/${VERSION}/build_${BUILD_NUMBER}
