MAJOR=11
MINOR=0
SERVICEPACK=0
BUILD_NUMBER=14800
#For milestone and ga
MILESTONE=ga
#For patch
PATCH_NUMBER=1
        #xap | dotnet | cpp | cloudify
PATCH_TYPE=xap


VERSION=${MAJOR}.${MINOR}.${SERVICEPACK}

REPOSITORY=/export/builds
BUILD_DIR=${REPOSITORY}/${VERSION}/build_${BUILD_NUMBER}
